channels:
  start_date: "today"
  mine: true
  part:
    [
      "brandingSettings",
      "contentDetails",
      "contentOwnerDetails",
      "id",
      "localizations",
      "snippet",
      "statistics",
      "status",
      "topicDetails",
    ]

basic_stats:
  start_date: "2_days_ago"
  end_date: "2_days_ago"
  interval: "1_day"
  metrics: ["views"]
  dimensions: ["day", "insightTrafficSourceType"]
  sort: "day"

source_stats:
  start_date: "2_days_ago"
  end_date: "2_days_ago"
  interval: "1_day"
  metrics:
    [
      "views",
      "estimatedMinutesWatched",
      "averageViewDuration",
      "likes",
      "dislikes",
      "comments",
      "subscribersGained",
      "subscribersLost",
    ]
  dimensions: ["day"]

traffic_source:
  start_date: "2_days_ago"
  end_date: "2_days_ago"
  interval: "1_day"
  dimensions: ["day", "insightTrafficSourceType"]
  metrics: ["views", "estimatedMinutesWatched"]

video_stats:
  start_date: "2_days_ago"
  end_date: "2_days_ago"
  interval: "1_day"
  metrics:
    [
      "views",
      "estimatedMinutesWatched",
      "averageViewDuration",
      "likes",
      "dislikes",
      "comments",
      "subscribersGained",
      "subscribersLost",
    ]
  dimensions: ["day"]
  sort: "day"
